# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # An appender named "stdout" that writes to stdout
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f %Z)(utc)} [{l:<5}] {f}:{L} - {m} {n}"

  # An appender named "requests" that writes to a file with a custom pattern encoder
  to_file:
    kind: rolling_file
    path: "echos.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f %Z)(utc)} [{l:<5}] {f}:{L} - {m} {n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 16kb
      roller:
        kind: fixed_window
        base: 1
        count: 5
        pattern: "echos.log.{}"

# Set the default logging level to "warn" and attach the "stdout" appender to the root
root:
  level: info
  appenders:
    - stdout
    - to_file