refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  requests:
    kind: file
  roll: #Define appenders of rooling_file
    kind: rolling_file
    path: "roll.log"
    append: true
    encoder:
      kind: pattern
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 256 #Limit size to 1024Byte
      roller:
        kind: fixed_window
        pattern: 'roll.log.{}'
        base: 1
        count: 50
root:
  level: info
  appenders:
    - stdout
    - roll
    - requests
